services:
  gotenberg:
    image: gotenberg/gotenberg:8
  docombine:
    build: backend
    depends_on:
      - gotenberg
    environment:
      - GOTENBERG_URL=http://gotenberg:3000
      - PORT=3000
    ports:
      - "3000:3000"
  nginx:
    build: .
    depends_on:
      - docombine
    ports:
      - "80:80"