services:
  gotenberg:
    image: gotenberg/gotenberg:8
  docombine:
    build: .
    image: docombine
    ports:
      - "8080:8080"
    depends_on:
      - gotenberg
    environment:
      - GOTENBERG_URL=http://gotenberg:3000
      - PORT=8080
      - SERVE_FILES=true